version: 2
updates:
- package-ecosystem: "npm"
  directory: "/"
  schedule:
    interval: "daily"
    time: "11:00"
    timezone: "Japan"
  labels:
  - "dependencies-npm"
  commit-message:
    prefix: "deps(npm-dev)"

- package-ecosystem: "npm"
  directory: "/exampleSite"
  schedule:
    interval: "daily"
    time: "11:00"
    timezone: "Japan"
  labels:
  - "dependencies-npm"
  commit-message:
    prefix: "deps(npm)"

- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "daily"
    time: "11:00"
    timezone: "Japan"
  labels:
  - "cicd"
  commit-message:
    prefix: "ci"

- package-ecosystem: "gomod"
  directory: "/deps"
  schedule:
    interval: "daily"
    time: "11:00"
    timezone: "Japan"
  commit-message:
    prefix: "deps(gomod)"
